### ISSUE TITLE
font problems on firefox

### ISSUE THREAD

**Issue by florpor** [noamoss/notifier#29]
![screenshot from 2016-06-06 19-15-54](https://cloud.githubusercontent.com/assets/1809093/15829160/2e8be61c-2c1b-11e6-92c6-8d43e2306c76.png)

can't see hebrew letters...
firefox version is 46.0.1 running on linux (chromium on linux renders the page correctly)

**Comment by noamoss** [comment]
@florpor wired, tried also on firefox 46.0.1 on ubuntu - works fine. Could you provide further details?

**Comment by florpor** [comment]
it seems to be a problem on my machine i guess...
when the font-weight is light (as is set in bootstrap's css) firefox seems to think open sans is good for the hebrew characters (which it isn't) and doesn't load a complimentary locally installed font for them, but when i change the font-weight to normal it does load the local font just fine... not sure what its deal is but it's probably a firefox issue.

closing...
